steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/job-finder-project-437300/image-registry/job-finder-api-v2',
        '-f',
        'Dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/job-finder-project-437300/image-registry/job-finder-api-v2',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
