version: '3.9'

services:
  api:
    container_name: 'job-finder-api'
    build:
      context: .
      target: prod
      dockerfile: Dockerfile.prod
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - SESSION_KEY=${SESSION_KEY}
      - URL_CLIENT=${URL_CLIENT}
      - URL_CLIENT_LOGIN_REDIRECT=${URL_CLIENT_LOGIN_REDIRECT}
      - APP_VERSION=${APP_VERSION}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - DB_SSL_ENABLED=${DB_SSL_ENABLED}
      - DB_SSL_REJECT_UNAUTHORIZED=${DB_SSL_REJECT_UNAUTHORIZED}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET_KEY=${FACEBOOK_APP_SECRET_KEY}
      - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}
      - SENDGRID_ACCESS_KEY=${SENDGRID_ACCESS_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - SENDGRID_SANDBOX_MODE=${SENDGRID_SANDBOX_MODE}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - '4000:4000'
