version: '3.9'

services:
  db:
    build:
      context: docker/postgres/
      dockerfile: Dockerfile.dev
    container_name: ${DB_NAME}
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
